on:
  push:
    branches:
      - master







jobs:
  build:
    runs-on: ubuntu-latest




    steps:
      

        -uses: actions/checout@v3

        -name: "docker login"
          run: docker login --username ${{DOCKER_USERNAME}} --password ${{DOCKER_TOKEN}}


       


     



