on:
  push:
    branches:
      - master







jobs:
  build:
    runs-on: ubuntu-latest




    steps:
      

        -uses: actions/checout@v3

        -name: "docker login"
          run: docker login --username ${{DOCKER_USERNAME}} --password ${{DOCKER_TOKEN}}

          -name: "building docker image"
            run: docker build -t ${{DOCKER_USERNAME}}/myimage

          -name: "pushing to docker hub" 
            run: docker push ${{DOCKER_USERNAME}}/myimage


       


     



